# Generated by Django 5.0.2 on 2024-03-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salario',
            name='extra_diciembre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salario',
            name='extra_junio',
            field=models.BooleanField(default=False),
        ),
    ]
