# Generated by Django 5.0.2 on 2024-03-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
